### ISSUE TITLE
Fail to send emails in some cases

### ISSUE THREAD

**Issue by geriguy43** [andrewscaya/mod_simpleemailform#19]
At our webpage almost every page contains a contact form (always the same).

If the visitor opens one (or several) new tab(s) and tries to send email from the first (original) tab, Simple Email Form fails to send out the email. It only reloads the page. Visitors need to repush the send button (But nobody does because visitors thinks they have sent out the email.)

To replicate the error (just an example):
First open this: http://bestmachinery.hu/foldmunkagepek

After that open other subpages, for example:
http://bestmachinery.hu/megujult-a-best-machinery-daralo-kinalata
and
http://bestmachinery.hu/hulladek-feldolgozasa
and
http://bestmachinery.hu/targoncak-es-raktartechnika

Now fill the form at first page:
http://bestmachinery.hu/foldmunkagepek

And it won't work.

**I think it is some token/session error. What do you think?**

I'm using the latest version (2.0.1) with "classic" setting. But the problem was always here! 
(I started to use Simple Email Form 3 or 4 years ago).
Joomla is latest one.

**Comment by andrewscaya** [comment]
@geriguy43 --

We will have a look into it even though SEF's classic mode is now deprecated.

Thanks for reporting the issue!

Best regards,

Andrew

**Comment by andrewscaya** [comment]
@martinbeaudry  --

Can you have a look into this, please?  Maybe check if the CSRF tokens are correctly stored in the session and/or the instance identifiers are correctly set in the 'classic' mode of SEF.  Even though SEF's classic mode is now deprecated, maybe we can add one last bug fix (or two!)? ;-)

BTW, it is safe to fork from the 'develop' branch for this one.

Many thanks!

Andrew

**Comment by andrewscaya** [comment]
Just created branch 2.1.0-dev for our future release in August.

@martinbeaudry: changes to the official documentation can now be committed.

**Comment by andrewscaya** [comment]
@martinbeaudry: Branch 'issue19' has been deleted.

**Comment by martinbeaudry** [comment]
@geriguy43 Thanks for reporting this issue.

I had a look at your website and made some tests. The problem seems to be that all of your forms have the same "Form Instance" (see the second field in simple email form's "Advanced" options). To have the form behave the right way, you can either:
- use the "Duplicate" Joomla feature to install multiple SEF modules, and give each one a different Form Instance; OR
- use JForm, as the new version can handle multiple forms with the same ID.

I now realize that the documentation isn't very clear on this issue. It reads: "If you use more than one simple email form on the same page, you need to give each one a unique number to differentiate them from the other forms."

I'll change it to: "If you use more than one classic simple email forms on your website, even on different pages, you need to give each one of them a unique number to differentiate them from each other."

**Comment by andrewscaya** [comment]
@martinbeaudry: Many thanks for your prompt response!  I will close this thread once you will have committed the changes to the documentation.  This modification will be included in release 2.1.0 of SEF (August 2017).

**Comment by andrewscaya** [comment]
@geriguy43 --

You can have a look at the official documentation concerning 'Form Instances' here:
http://simple-email-form.readthedocs.io/en/stable/advanced_options.html#index-1

Also, thanks for being a long-term supporter of SEF!

Best regards,

Andrew

**Comment by geriguy43** [comment]
Thanks for the quick help.

It is a huge work to duplicate the modules because at our site ther are around 100-150 pages were there are this particular from. I need to duplicate it 150 times and add different numbers at advanced. (After that at articles, I need to change the module numbers step by step...)

For me JForm isn't working properly. The textbox became huge with the editor on the top and I can't adjust the size of the box. It would be good to have a textbox what was/is in the deprecated version.

But this is the smaller problem. Here is the big one: Even if I should get the emails in html format, I always get them in plain text. Additionally some of the typed in texts are missing. For example I get only the first few characters of the textbox field.

This is why neither solution is perfect :(
At least using JForm solves the original problem but generates a few new one.

Any more suggestion? Maybe somewhere at Joomla settings I disabled html email sending? I don't think so.

**Comment by geriguy43** [comment]
Here is the test result of the received email made with JForm version (now you can't test, but if you are interested, I can switch this on of the Slovakian version of our site at bestmachinery.sk because that one is not a heavily visited website)

Article Title: Stroje na zemné práce
* Meno:: Gergo
* Telefonné číslo:: Nem
Spoločnosť:: nem
*Obec, Mesto:: nem
* Predmet oznámenia:: <p><span style="text-decoration: line-through;"><s
tárgy:: Best Machinery - SZLOVÁK érdeklődés

Subject is also empty if I use the JForm ("tárgy::" should be the subject, it is a hidden field"

"* Predmet oznámenia::" is the mentioned textbox. The content of it was much-much longer, but it have been cut out.

I got the emails like this, not github converted it to plaintext...

**Comment by geriguy43** [comment]
Well, github changed it, so here is the original:
`Article Title: Stroje na zemné práce
* Meno:: Gergo
* Telefonné číslo:: Nem
Spoločnosť:: nem
*Obec, Mesto:: nem
* Predmet oznámenia:: <p><span style="text-decoration: line-through;"><s
tárgy:: Best Machinery - SZLOVÁK érdeklődés`

**Comment by andrewscaya** [comment]
@geriguy43 --

Since version 2.0.0 of SEF, the module is now fully integrated with the Joomla CMS. The JForm mode is very powerful as you now have full control over all elements of the SEF module.  To modify the TinyMCE editor's (JForm textarea) appearance, just go to "Extensions -> Plugin Manager -> Editor - TinyMCE -> Advanced settings" in your Joomla website's Administration panel and modify width & height according to your needs.

Best regards,

Andrew

**Comment by andrewscaya** [comment]
Request completed.

**Comment by andrewscaya** [comment]
@geriguy43 --

One last thing, concerning the length of the textarea section of your email, please make sure that you set the size of the field (ex. '50,50') in the SEF Admin panel as we filter the maximum allowed length of the contents of each field accordingly.  This is for security reasons as it prevents nasty things from happening like buffer overflows and remote code execution due to an uploaded binary in the field...! :)

Best regards,

Andrew

**Comment by geriguy43** [comment]
Ok, I try it. Thank you! And the last question: why I receive the emails in plain text only? 

This is the part of the header of the received mail:
X-Mailer: PHPMailer 5.2.16 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

**Comment by andrewscaya** [comment]
@geriguy43 --

For security reasons, we send the HTML out as a 'text/plain' document.  You can use the HTML as you see fit afterwards.  Otherwise, any email sent with our module could be considered as very insecure as it could allow a hacker to run code through your MUA.  If you wish to use it as HTML, you can extract the HTML and save it once you are sure the HTML is safe (change the MIME type manually - create a ".htm" document for example).

Best regards,

Andrew

**Comment by geriguy43** [comment]
OK, thank you, I understand. But this way the TinyMCE is totally useless for the visitor.

**Comment by andrewscaya** [comment]
@geriguy43 --

Well, no.  SEF sends the HTML in plaintext format and you decide what to do with it.  We might consider adding a setting in the admin panel eventually that will allow the website administrator (at his own risk) to set the email's content-type header to text/html for that part of the email.  But, for now, let's keep it, well, simple!

Best regards,

Andrew

**Comment by geriguy43** [comment]
Well, I could manage to set up correctly the JForm versions of the modules. Now the forms work flawlessly.
I am satisified with the design too: ( http://bestmachinery.hu/targoncak-es-raktartechnika for example)

But I found an other issue - I think it is a bug:

I am using a hidden subject field with a predefinied constant value at "default value of field X. (The text is shorter than the maximum allowed.)  I would like to get every email with this constant field in the subject.

But after I changed to JForm from classic, I always get the emails without any subject...

Why? 

![2017-04-09_204256](https://cloud.githubusercontent.com/assets/27052436/24839991/27c297d6-1d65-11e7-902f-374d1a84f94a.jpg)

![2017-04-09_204506](https://cloud.githubusercontent.com/assets/27052436/24840009/737814d0-1d65-11e7-9af7-07a00bbcb2cf.jpg)

On my picture "nincs tárgy" means "no subject".

**Comment by andrewscaya** [comment]
@geriguy43 --

Can I ask you why you wish to make the subject field hidden since it would not stop a user from modifying its value and would bar the field from constraint validation (no client and/or server-side validation and filtering)?

Our intent is to abandon this 'classic' mode's feature and uphold the W3C Recommendations on this issue (see [here](https://www.w3.org/TR/html5/forms.html#hidden-state-(type=hidden)) as the hidden subject field would then be barred from constraint validation (insecure).

An easy workaround would be to install an extension that allows you to add custom JavaScript scripts (see [here](https://www.ostraining.com/blog/joomla/custom-js/)) and "disable" the input field on the client-side (ex. "document.getElementById('foo').disabled = true;") while still benefiting from SEF's server-side validation and filtering before including the string in the email's subject heading.

Best regards,

Andrew

**Comment by dbierer** [comment]
Andrew --I added a feature "hidden" to the original Simple Email Form which functions as follows:--It allows a programmatically defined constant value to be passed as a parameter in the return email--This value will *always* be present, and is often used to identify form postings from different places on the website: i.e. a way of identifying the page from which the form posted in the case where multiple pages feature the form.Yours,DougOn April 12, 2017 at 11:56 AM Andrew Caya <notifications@github.com> wrote:@geriguy43 --Can I ask you why you wish to make the subject field hidden since it would not stop a user from modifying its value and would bar the field from constraint validation (no client and/or server-side validation and filtering)?Our intent is to abandon this 'classic' mode's feature and uphold the W3C Recommendations on this issue (see here as the hidden subject field would then be barred from constraint validation (insecure).An easy workaround would be to install an extension that allows you to add custom JavaScript scripts (see here) and "disable" the input field on the client-side (ex. "document.getElementById('foo').disabled = true;") while still benefiting from SEF's server-side validation and filtering before including the string in the email's subject heading.Best regards,Andrew—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by andrewscaya** [comment]
@dbierer 

Doug --

The "hidden" feature has not been modified as such in version 2.x.  But, it is true that, as of version 2.0.0, the "hidden" feature can no longer be applied to the 'From' and the 'Subject' fields (see [source](https://github.com/andrewscaya/mod_simpleemailform/blob/master/sefv2/modsimpleemailform.php#L1722)), as this allows these fields to be submitted to specific constraint validations (ex. email validation).  I would therefore strongly advise against changing this new way of using the "hidden" feature.

Also, we are leaving these possible combinations ('From' and/or 'Subject' + "hidden") unmodified in SEF's admin panel for now, as we do want to make sure that the 'classic' mode remains fully functional until it is removed in version 3.0.0.

Yours,

Andrew
