### ISSUE TITLE
Error with new JCE editor (2.6.14. and 2.6.15.)

### ISSUE THREAD

**Issue by geriguy43** [andrewscaya/mod_simpleemailform#20]
With the newest (updated) version of JCE editor, the textbox of Simple Email Forms are fails to load. I think it can be a relevant issue, because lots of users changed the TinyMCE editor to JCE.

You can check. Here the textbox renders good:
http://bestmachinery.hu/foldmunkagepek
(JCE editor 2.6.12)

Here it isn't:
http://bestmachinery.sk/stroje-na-zemne-prace
(JCE editor 2.6.15)

**Comment by andrewscaya** [comment]
Geriguy43 --

We will definitely have a look into this before the next release scheduled to be published this summer.

Many thanks!

Best regards,

Andrew

**Comment by andrewscaya** [comment]
Issue is under active analysis.

**Comment by andrewscaya** [comment]
@geriguy43 --

As far as we can see, it seems that the JCE Editor doesn't register its editor with Joomla's JForm object. I've tried running the TinyMCE, CodeMirror and None editors on the most recent versions of Joomla and Simple Email Form (with the JForm Form Type, since the Classic Form Type is now deprecated), and they all work as expected. We can only suggest that you submit this issue to JCE Editor's maintainer @ryandemmer.

If you have any other questions, please do not hesitate to contact us again.

Thanks for using the Simple Email Form!

Best regards,

Andrew

**Comment by geriguy43** [comment]
Dear Andrew! Just to inform you, it was a bug at JCE editor, they solved it at version 2.6.17. Sorry about that I didn't tell it earlier. From that version, it works flawlessly. 

Thanks again!

Best regards,

Gergely

**Comment by andrewscaya** [comment]
@geriguy43 --

No problem. Glad to see everything is working now!

Thanks for using the Simple Email Form module!

Best regards,

Andrew
