### ISSUE TITLE
From field not sending

### ISSUE THREAD

**Issue by m3vip** [andrewscaya/mod_simpleemailform#30]
I have added it as a module in this web "http://www.wifiair.es/contacto", there are 4 fields. but i always get 3 of them, the first (Email From), its always the same "web.wifiair@gmail.com"

![image](https://user-images.githubusercontent.com/36934472/36810599-75f5d09c-1ccb-11e8-8436-5ecf7cd6705b.png)
This is my configuration done:

![image](https://user-images.githubusercontent.com/36934472/36810661-a10705a8-1ccb-11e8-87fb-cae5050b0537.png)

------------------------------------------------------------

![image](https://user-images.githubusercontent.com/36934472/36810766-ffd9ade2-1ccb-11e8-994e-96de5c949a22.png)

**Comment by andrewscaya** [comment]
Hi @m3vip,

Yes, this is normal and it is the module's expected behavior. The form's 'From' field is used to actually send the email. This is shown in your first screenshot, as the email was received from 'web.wifiair@gmail.com'.

Thank you for your interest in the Simple Email Form module.

Best regards,

Andrew
