### ISSUE TITLE
Subjet of @mail

### ISSUE THREAD

**Issue by operon** [andrewscaya/mod_simpleemailform#33]
When I receive the @ mail, I do not have a "subject"?

I configured a hidden field "subjet" with "message subject" in default value.

**Comment by andrewscaya** [comment]
Hello @operon,

Please see my reply here : [https://github.com/andrewscaya/mod_simpleemailform/issues/19#issuecomment-293685479](https://github.com/andrewscaya/mod_simpleemailform/issues/19#issuecomment-293685479)

If you have any further questions, please do not hesitate to reply to this message.

Best regards,

Andrew Caya

**Comment by operon** [comment]
Hello,

I read # 19 but I do not see the connection with my problem

**Comment by andrewscaya** [comment]
Hi @operon,

For security reasons, the Subject field can no longer be a hidden field, as HTML hidden fields cannot be thoroughly filtered, validated and sanitized, since they can contain just about anything.

Quote from #19:

> The "hidden" feature has not been modified as such in version 2.x. But, it is true that, as of version 2.0.0, the "hidden" feature can no longer be applied to the 'From' and the 'Subject' fields (see [source](https://github.com/andrewscaya/mod_simpleemailform/blob/master/sefv2/modsimpleemailform.php#L1722)), as this allows these fields to be submitted to specific constraint validations (ex. email validation). I would therefore strongly advise against changing this new way of using the "hidden" feature.
> 
> Also, we are leaving these possible combinations ('From' and/or 'Subject' + "hidden") unmodified in SEF's admin panel for now, as we do want to make sure that the 'classic' mode remains fully functional until it is removed in version 3.0.0.

If you have any further questions, please do not hesitate to send them to us.

Many thanks for your interest in the Simple Email Form module.

Best regards,

Andrew Caya

**Comment by operon** [comment]
Thanks, it is ok now.

Do not use "hidden"
