### ISSUE TITLE
With Joomls settings Article->Nocaptcha, Jform option captcha hidden!! 

### ISSUE THREAD

**Issue by nicsym** [andrewscaya/mod_simpleemailform#38]
After setting the Article option on no-captcha (article front-end editting), the form has no j-form captcha anymore (the classic captcha works well in this mode).
When placed this same form in a jevent arti cle, the captcha works well.

**Comment by andrewscaya** [comment]
@nicsym --

This seems to be expected behavior, as SEF now uses Joomla's integrated captcha module. We will see if there is a workaround for this issue, but if not, you will have to open an issue with the Joomla CMS core team, as they are responsible for maintaining this specific functionality.

We will get back to you as soon as possible.

Many thanks for your interest in the Simple Email Form module!

Best regards,

Andrew

**Comment by andrewscaya** [comment]
After verification, this is expected behavior. Turning off captcha rendering in Joomla's default captcha module will indeed turn off captcha rendering in SEF.
