### ISSUE TITLE
Sizing of textarea field does not work with JForm

### ISSUE THREAD

**Issue by ruedigerO** [andrewscaya/mod_simpleemailform#39]
Sizing of a textarea field does not work with JFom, (size is independent of the settings)
In Classic mode the same settings are working well
(Joomla 3.9.2, PHP 7.2)

**Comment by andrewscaya** [comment]
@ruedigerO --

Since version 2.0.0 of SEF, the module is now fully integrated with the Joomla CMS. The JForm mode is very powerful as you now have full control over all elements of the SEF module. To modify the TinyMCE editor's (JForm textarea) appearance, just go to "Extensions -> Plugin Manager -> Editor - TinyMCE -> Advanced settings" in your Joomla website's Administration panel and modify width & height according to your needs.

Best regards,

Andrew
