### ISSUE TITLE
Marking subject field as hidden does not work with JForm 

### ISSUE THREAD

**Issue by ruedigerO** [andrewscaya/mod_simpleemailform#40]
If the subject field is set to hidden (in JForm mode) the resulting email contains no subject

**Comment by andrewscaya** [comment]
@ruedigerO --

For security reasons, the Subject field can no longer be a hidden field, as HTML hidden fields cannot be thoroughly filtered, validated and sanitized, since they can contain just about anything.

Quote from #19:

> The "hidden" feature has not been modified as such in version 2.x. But, it is true that, as of version 2.0.0, the "hidden" feature can no longer be applied to the 'From' and the 'Subject' fields (see [source](https://github.com/andrewscaya/mod_simpleemailform/blob/master/sefv2/modsimpleemailform.php#L1722)), as this allows these fields to be submitted to specific constraint validations (ex. email validation). I would therefore strongly advise against changing this new way of using the "hidden" feature.
> 
> Also, we are leaving these possible combinations ('From' and/or 'Subject' + "hidden") unmodified in SEF's admin panel for now, as we do want to make sure that the 'classic' mode remains fully functional until it is removed in version 3.0.0.

If you have any further questions, please do not hesitate to send them to us.

Many thanks for your interest in the Simple Email Form module.

Best regards,

Andrew Caya

**Comment by ruedigerO** [comment]
Hi Andrew

thanks for your clarification.
Maybe it would be a good idea to mention this in the documentation

Best regards
Rüdiger

**Comment by andrewscaya** [comment]
Hi @ruediger,

Yes, we will add a note in the next release's documentation.

Many thanks!
